
package StudentUI;

import Data.Models.ModelCourse;
import Swing.EventItem;

public class studentDashboard extends javax.swing.JPanel {
    private EventItem event;
    public void setEvent(EventItem event) {
        this.event = event;
        System.out.println("Event handler set for StudentCourseBox.");
    }
    public studentDashboard() {
        initComponents();
        
    }
    public void addItem(ModelCourse data) {
    if (data == null) {
        System.out.println("Error: ModelCourse data is null.");
        return;
    }

    StudentCourseBox studentbox = new StudentCourseBox();
    studentbox.setData(data);

    if (Student.data == null || Student.data.getStudentid() == null) {
        System.out.println("Error: Student data or ID is null.");
        return;
    }
    
    studentbox.studentId = Student.data.getStudentid();
    studentbox.onClick(event);
    panelItem1.add(studentbox);
    refreshPanel();
    System.out.println("Added course: " + data.getCourseName());
    System.out.println("Data set in StudentCourseBox: " + studentbox.data.getCourseName());
}


    private void refreshPanel() {
    panelItem1.repaint();
    panelItem1.revalidate();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelItem1 = new Swing.PanelItem();

        jScrollPane1.setViewportView(panelItem1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public Swing.PanelItem panelItem1;
    // End of variables declaration//GEN-END:variables
}
