/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TeacherUI.TeacherPanels;

import TeacherUI.TeacherBoxes.CourseBox;
import Data.Models.ModelCourse;
import Swing.EventItem;

/**
 *
 * @author User
 */
public class taecherDashboard extends javax.swing.JPanel {

    
    public void setEvent(EventItem event) {
        this.event = event;
    }
    public taecherDashboard() {
        initComponents();
    }
    private EventItem event;
     public void addItem(ModelCourse data) {
        CourseBox course = new CourseBox();
        course.setData(data);
        course.onClick1(event); // Attach the event handler
        panelItem1.add(course);
        refreshPanel();
    }

    private void refreshPanel() {
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelItem1 = new Swing.PanelItem();

        jScrollPane2.setViewportView(panelItem1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public Swing.PanelItem panelItem1;
    // End of variables declaration//GEN-END:variables
}
