/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import Data.Controller.UserController;
import Data.Models.ModelFacultyUser;
import TeacherUI.TeacherMain.Teacher;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FacultyLogin extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public FacultyLogin() {
        initComponents();
    }
    
    public void login() {
        txtUser.grabFocus();
    }

    public void addEventRegister(ActionListener event) {
        cmdRegister.addActionListener(event);
    }
    public void addEventBack(ActionListener event) {
        cmdBackFront.addActionListener(event);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTextField1 = new Swing.MyTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        panelBorder1 = new Swing.PanelBorder();
        loginBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pictureBox2 = new Swing.PictureBox();
        cmdBackFront = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(41, 78, 89));
        jPanel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPanel1InputMethodTextChanged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        cmdRegister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmdRegister.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegister.setText("Sign up");
        cmdRegister.setBorderPainted(false);
        cmdRegister.setContentAreaFilled(false);
        cmdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't have an account yet?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 30));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 287, 36));

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 287, 36));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setContentAreaFilled(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        panelBorder1.add(loginBtn);
        loginBtn.setBounds(0, 0, 100, 30);

        jPanel1.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 100, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 103, 60, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, 10));

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-back-50.png"))); // NOI18N

        cmdBackFront.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmdBackFront.setForeground(new java.awt.Color(255, 255, 255));
        cmdBackFront.setBorderPainted(false);
        cmdBackFront.setContentAreaFilled(false);
        cmdBackFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackFrontActionPerformed(evt);
            }
        });
        pictureBox2.add(cmdBackFront);
        cmdBackFront.setBounds(0, 0, 30, 30);

        jPanel1.add(pictureBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1InputMethodTextChanged

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
   String username = txtUser.getText().trim();
char[] password = txtPass.getPassword();

// Validate input fields
if (username.isEmpty() || password.length == 0) {
    JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Validation Error", JOptionPane.WARNING_MESSAGE);
    return; // Exit if validation fails
}

// Create a faculty user object for login
ModelFacultyUser loginUser = new ModelFacultyUser("", username, password, "");
UserController controller = new UserController();

try {
    // Attempt to log in the user
    ModelFacultyUser loggedInUser = controller.LogInFaculty(loginUser);

    if (loggedInUser != null) {
        ModelFacultyUser.UserRole role = loggedInUser.getRole(); // Retrieve the user's role
        Component topLevelContainer = FacultyLogin.this.getTopLevelAncestor();

        // Hide the current JFrame if it's a top-level container
        if (topLevelContainer instanceof JFrame jFrame) {
            jFrame.setVisible(false);
        }

        if (role == ModelFacultyUser.UserRole.ADMIN) {
            // If the user is an admin, open the Teacher panel
            String fullnameData = loggedInUser.getFullname();
            String teacheridData = loggedInUser.getTeacherid();

            Teacher teacherUI = new Teacher();
            teacherUI.teacherId.setText(teacheridData);
            teacherUI.fullName1.setText(fullnameData); // Set the fullname in the Teacher UI
            teacherUI.setVisible(true);
        } else {
            // If the user is not an admin, deny access
            JOptionPane.showMessageDialog(this, "Access denied. You do not have administrative privileges.", "Access Denied", JOptionPane.ERROR_MESSAGE);

            // Show the login window again
            if (topLevelContainer instanceof JFrame jFrame) {
                jFrame.setVisible(true);
            }
        }
    } else {
        // If login failed, show an error message
        JOptionPane.showMessageDialog(this, "Login failed. Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception ex) {
    Logger.getLogger(FacultyLogin.class.getName()).log(Level.SEVERE, "Unexpected error during login", ex);
    JOptionPane.showMessageDialog(this, "An unexpected error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_loginBtnActionPerformed

    private void cmdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdRegisterActionPerformed

    private void cmdBackFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackFrontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBackFrontActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String username = txtUser.getText();
        char[] password = txtPass.getPassword();
        if (username.isEmpty() || password.length == 0) {
    JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Validation Error", JOptionPane.WARNING_MESSAGE);
    return; // Exit if validation fails
}

        // Create a faculty user object for login
        ModelFacultyUser loginUser = new ModelFacultyUser("", username, password, "");
        UserController controller = new UserController();

        try {
            // Attempt to log in the user
            ModelFacultyUser loggedInUser = controller.LogInFaculty(loginUser);

            if (loggedInUser != null) {
                ModelFacultyUser.UserRole role = loggedInUser.getRole(); // Retrieve the user's role
                Component topLevelContainer = FacultyLogin.this.getTopLevelAncestor();

                // Hide the current JFrame if it's a top-level container
                if (topLevelContainer instanceof JFrame jFrame) {
                    jFrame.setVisible(false);
                }

                if (role == ModelFacultyUser.UserRole.ADMIN) {
                    // If the user is an admin, open the Teacher panel
                    String fullnameData = loggedInUser.getFullname();
                    String teacheridData = loggedInUser.getTeacherid();

                    Teacher teacherUI = new Teacher();
                    teacherUI.teacherId.setText(teacheridData);
                    teacherUI.fullName1.setText(fullnameData); // Set the fullname in the Teacher UI
                    teacherUI.setVisible(true);
                } else {
                    // If the user is not an admin, deny access
                    JOptionPane.showMessageDialog(this, "Access denied. Invalid username or password.", "Access Denied", JOptionPane.ERROR_MESSAGE);

                    // Show the login window again
                    if (topLevelContainer instanceof JFrame jFrame) {
                        jFrame.setVisible(true);
                    }
                }
            } else {
                // If login failed, show an error message
                JOptionPane.showMessageDialog(null, "Login failed. Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FacultyLogin.class.getName()).log(Level.SEVERE, "Unexpected error during login", ex);
            JOptionPane.showMessageDialog(this, "An unexpected error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_txtPassKeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
         if (jCheckBox1.isSelected()) {
        txtPass.setEchoChar((char) 0); // Reveal password
    } else {
        txtPass.setEchoChar('\u2022'); // Mask password with black dots
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBackFront;
    private javax.swing.JButton cmdRegister;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton loginBtn;
    private Swing.MyTextField myTextField1;
    private Swing.PanelBorder panelBorder1;
    private Swing.PictureBox pictureBox2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
