/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import Data.Controller.UserController;
import Data.Models.ModelStudentUser;
import StudentUI.Student;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;


/**
 *
 * @author User
 */
public class StudentLogin extends javax.swing.JPanel {

    /**
     * Creates new form StudentLogin
     */
    public StudentLogin() {
        initComponents();
    }
    public void addEventStudentLogin(ActionListener event) {
        cmdStudentRegister.addActionListener(event);
    }
    public void addEventBack(ActionListener event) {
        cmdBack.addActionListener(event);
    }
        public void addEventRegister(ActionListener event) {
        cmdStudentRegister.addActionListener(event);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdStudentRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        panelBorder1 = new Swing.PanelBorder();
        loginBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pictureBox2 = new Swing.PictureBox();
        cmdBack = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(41, 78, 89));
        jPanel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPanel1InputMethodTextChanged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 153, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 243, -1, -1));

        cmdStudentRegister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmdStudentRegister.setForeground(new java.awt.Color(255, 255, 255));
        cmdStudentRegister.setText("Sign up");
        cmdStudentRegister.setBorderPainted(false);
        cmdStudentRegister.setContentAreaFilled(false);
        cmdStudentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStudentRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(cmdStudentRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 93, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't have an account yet?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 93, -1, 30));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 176, 287, 36));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 266, 287, 36));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setContentAreaFilled(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        panelBorder1.add(loginBtn);
        loginBtn.setBounds(0, 0, 100, 30);

        jPanel1.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 100, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 113, 60, 10));

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-back-50.png"))); // NOI18N

        cmdBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmdBack.setForeground(new java.awt.Color(255, 255, 255));
        cmdBack.setBorderPainted(false);
        cmdBack.setContentAreaFilled(false);
        cmdBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackActionPerformed(evt);
            }
        });
        pictureBox2.add(cmdBack);
        cmdBack.setBounds(0, 0, 30, 30);

        jPanel1.add(pictureBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdStudentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStudentRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdStudentRegisterActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
String username = txtUser.getText();
char[] password = txtPass.getPassword();

// Validate input
if (username == null || username.trim().isEmpty() || password == null || password.length == 0) {
    JOptionPane.showMessageDialog(this, "Please fill in both username and password.", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}

// Create a user model
ModelStudentUser loginUser = new ModelStudentUser(username, password, "", "", "");

UserController controller = new UserController();

try {
    // Attempt login and retrieve user details
    ModelStudentUser loggedInUser = controller.LogInStudent(loginUser);

    if (loggedInUser != null) {
        // Launch the student UI with the logged-in user data
        Student studentPanel = new Student(loggedInUser);
        studentPanel.setVisible(true);

        // Close the current login window
        Component topLevelContainer = SwingUtilities.getWindowAncestor(this);
        if (topLevelContainer instanceof JFrame frame) {
            frame.setVisible(false);
        }
    } else {
        // Invalid credentials
        JOptionPane.showMessageDialog(this, "Login failed. Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception ex) {
    // Handle unexpected errors
    Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, "Unexpected error during login", ex);
    JOptionPane.showMessageDialog(this, "An unexpected error occurred. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_loginBtnActionPerformed

    private void jPanel1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1InputMethodTextChanged

    private void cmdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBackActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String username = txtUser.getText();
char[] password = txtPass.getPassword();

// Validate input
if (username == null || username.trim().isEmpty() || password == null || password.length == 0) {
    JOptionPane.showMessageDialog(this, "Please fill in both username and password.", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}

// Create a user model
ModelStudentUser loginUser = new ModelStudentUser(username, password, "", "", "");

UserController controller = new UserController();

try {
    // Attempt login and retrieve user details
    ModelStudentUser loggedInUser = controller.LogInStudent(loginUser);

    if (loggedInUser != null) {
        // Launch the student UI with the logged-in user data
        Student studentPanel = new Student(loggedInUser);
        studentPanel.setVisible(true);

        // Close the current login window
        Component topLevelContainer = SwingUtilities.getWindowAncestor(this);
        if (topLevelContainer instanceof JFrame frame) {
            frame.setVisible(false);
        }
    } else {
        // Invalid credentials
        JOptionPane.showMessageDialog(this, "Login failed. Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception ex) {
    // Handle unexpected errors
    Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, "Unexpected error during login", ex);
    JOptionPane.showMessageDialog(this, "An unexpected error occurred. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
}
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
        txtPass.setEchoChar((char) 0); // Reveal password
    } else {
        txtPass.setEchoChar('\u2022'); // Mask password with black dots
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdStudentRegister;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginBtn;
    private Swing.PanelBorder panelBorder1;
    private Swing.PictureBox pictureBox2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
